/**
 * Seed content — migrated verbatim from the legacy static site.
 *
 * Two jobs:
 *   1. Fallback for the public site while Supabase is not configured.
 *   2. Source data for the DB seed script (scripts/seed-db.mjs).
 *
 * No fabricated marketing copy — every value already existed on cangur.md.
 * `coaches` / `advertisements` are empty: the owner adds real ones in /admin.
 */

import type {
  Advertisement,
  Coach,
  GalleryImage,
  Hero,
  NavItem,
  PricingPlan,
  Product,
  Program,
  ScheduleSlot,
  SiteSettings,
  Testimonial,
} from "./types";

export const settings: SiteSettings = {
  clubName: "Cangur Boxing Club & Gym",
  phone: "+373 68 702 717",
  phoneDisplay: "+373 68 702 717",
  phoneHref: "+37368702717",
  phoneSecondary: null,
  phoneSecondaryHref: null,
  email: null,
  instagramUrl: "https://www.instagram.com/cangur_boxingclub/",
  instagramHandle: "@cangur_boxingclub",
  telegramUrl: null,
  facebookUrl: null,
  addressLine: {
    ru: "Кишинёв, Ботаника, Grădina Botanică 2",
    ro: "Chișinău, Botanica, Grădina Botanică 2",
    en: "Chișinău, Botanica, Grădina Botanică 2",
  },
  mapUrl:
    "https://www.google.com/maps/search/?api=1&query=Gradina+Botanica+2+Chisinau",
  workHours: {
    ru: "Понедельник — Воскресенье",
    ro: "Luni — Duminică",
    en: "Monday — Sunday",
  },
  hoursOpen: "07:00",
  hoursClose: "21:00",
  locationImageUrl: null,
  currency: "MDL",
  priceRange: "150–4000 MDL",
  ctaCallLabel: { ru: "Позвонить", ro: "Sună", en: "Call" },
  routeCtaLabel: {
    ru: "Открыть маршрут",
    ro: "Deschide traseul",
    en: "Open directions",
  },
  bookCtaLabel: {
    ru: "Записаться на тренировку",
    ro: "Înscrie-te la antrenament",
    en: "Book a training session",
  },
  defaultCtaLabel: { ru: "START NOW", ro: "ÎNCEPE ACUM", en: "START NOW" },
  defaultCtaUrl: "tel:+37368702717",
  announcement: { text: {}, url: null, active: false },
  logoUrl: null,
  ogImageUrl: null,
  seo: {
    title: {
      ru: "Cangur — боксёрский клуб в Кишинёве | Тренировки по боксу",
      ro: "Cangur — club de box în Chișinău | Antrenamente de box",
      en: "Cangur Boxing Club Chișinău | Boxing Training & Gym",
    },
    description: {
      ru: "Боксёрский клуб Cangur в Кишинёве, район Ботаника. Групповые и персональные тренировки по боксу для взрослых, девушек и детей. Абонемент от 1000 MDL.",
      ro: "Club de box Cangur în Chișinău, sectorul Botanica. Antrenamente de grup și individuale de box pentru adulți, femei și copii. Abonament de la 1000 MDL.",
      en: "Cangur boxing club in Chișinău, Botanica district. Group and personal boxing training for adults, women and kids. Membership from 1000 MDL.",
    },
    ogTitle: {},
    ogDescription: {},
  },
};

export const hero: Hero = {
  kicker: {
    ru: "CANGUR BOXING CLUB",
    ro: "CANGUR BOXING CLUB",
    en: "CANGUR BOXING CLUB",
  },
  headline: {
    ru: "READY TO FIGHT?",
    ro: "GATA DE LUPTĂ?",
    en: "READY TO FIGHT?",
  },
  subtitle: {
    ru: "JOIN CANGUR TODAY",
    ro: "ALĂTURĂ-TE CANGUR ASTĂZI",
    en: "JOIN CANGUR TODAY",
  },
  ctaLabel: { ru: "START NOW", ro: "ÎNCEPE ACUM", en: "START NOW" },
  ctaUrl: "tel:+37368702717",
  ctaEnabled: true,
  videoEnabled: true,
  posterUrl: "/video/hero-poster.jpg",
  videoDesktopUrl: "/video/hero.webm",
  videoMobileUrl: null,
};

export const navItems: NavItem[] = [
  { key: "programs", label: {}, visible: true, sortOrder: 1 },
  { key: "gallery", label: {}, visible: true, sortOrder: 2 },
  { key: "prices", label: {}, visible: true, sortOrder: 3 },
  { key: "shop", label: {}, visible: true, sortOrder: 4 },
  { key: "schedule", label: {}, visible: true, sortOrder: 5 },
  { key: "coaches", label: {}, visible: true, sortOrder: 6 },
  { key: "contacts", label: {}, visible: true, sortOrder: 7 },
];

export const programs: Program[] = [
  {
    id: "men",
    slug: "men",
    title: { ru: "Мужской бокс", ro: "Box pentru bărbați", en: "Men's boxing" },
    text: {
      ru: "Техника, мешки, лапы, выносливость и спарринги.",
      ro: "Tehnică, sac, palmare, rezistență și sparring.",
      en: "Technique, bags, pads, endurance and sparring.",
    },
    image: "/images/program-men.webp",
    badge: null,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 1,
  },
  {
    id: "women",
    slug: "women",
    title: { ru: "Женский бокс", ro: "Box feminin", en: "Women's boxing" },
    text: {
      ru: "Сила, координация, форма и уверенность.",
      ro: "Forță, coordonare, formă și încredere.",
      en: "Strength, coordination, fitness and confidence.",
    },
    image: "/images/program-women.webp",
    badge: null,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 2,
  },
  {
    id: "kids",
    slug: "kids",
    title: { ru: "Детский бокс", ro: "Box pentru copii", en: "Kids boxing" },
    text: {
      ru: "Дисциплина, реакция и безопасная техника.",
      ro: "Disciplină, reacție și tehnică sigură.",
      en: "Discipline, reactions and safe technique.",
    },
    image: "/images/program-kids.webp",
    badge: null,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 3,
  },
  {
    id: "personal",
    slug: "personal",
    title: { ru: "Персонально", ro: "Individual", en: "Personal training" },
    text: {
      ru: "Индивидуальный план и работа один на один.",
      ro: "Plan individual și lucru unu la unu.",
      en: "Individual plan and one-to-one coaching.",
    },
    image: "/images/program-personal.webp",
    badge: null,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 4,
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "group-month",
    slug: "group-month",
    title: { ru: "Групповой бокс", ro: "Box de grup", en: "Group boxing" },
    description: null,
    price: 1000,
    oldPrice: null,
    currency: "MDL",
    period: "month",
    periodLabel: null,
    sessionsCount: null,
    badge: { ru: "Популярно", ro: "Popular", en: "Popular" },
    featured: false,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 1,
  },
  {
    id: "group-single",
    slug: "group-single",
    title: {
      ru: "Разовая групповая",
      ro: "Antrenament de grup · o ședință",
      en: "Single group session",
    },
    description: null,
    price: 150,
    oldPrice: null,
    currency: "MDL",
    period: "session",
    periodLabel: null,
    sessionsCount: null,
    badge: null,
    featured: false,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 2,
  },
  {
    id: "personal-session",
    slug: "personal-session",
    title: { ru: "Персонально", ro: "Individual", en: "Personal training" },
    description: null,
    price: 450,
    oldPrice: null,
    currency: "MDL",
    period: "session",
    periodLabel: null,
    sessionsCount: null,
    badge: null,
    featured: true,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 3,
  },
  {
    id: "personal-10",
    slug: "personal-10",
    title: {
      ru: "10 персональных",
      ro: "10 antrenamente individuale",
      en: "10 personal sessions",
    },
    description: null,
    price: 4000,
    oldPrice: null,
    currency: "MDL",
    period: "package",
    periodLabel: null,
    sessionsCount: 10,
    badge: null,
    featured: false,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 4,
  },
  {
    id: "mini-class",
    slug: "mini-class",
    title: {
      ru: "Мини-класс · 2 человека",
      ro: "Mini-clasă · 2 persoane",
      en: "Mini class · 2 people",
    },
    description: null,
    price: 600,
    oldPrice: null,
    currency: "MDL",
    period: "session",
    periodLabel: null,
    sessionsCount: null,
    badge: null,
    featured: false,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 5,
  },
  {
    id: "mini-group",
    slug: "mini-group",
    title: { ru: "Мини-группа · 3+", ro: "Mini-grup · 3+", en: "Mini group · 3+" },
    description: null,
    price: 250,
    oldPrice: null,
    currency: "MDL",
    period: "session",
    periodLabel: null,
    sessionsCount: null,
    badge: null,
    featured: false,
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 6,
  },
];

const T_GROUP = { ru: "Групповой бокс", ro: "Box de grup", en: "Group boxing" };
const T_KIDS_59 = { ru: "Дети 5–9 лет", ro: "Copii 5–9 ani", en: "Kids 5–9" };
const T_KIDS_1016 = { ru: "Дети 10–16 лет", ro: "Copii 10–16 ani", en: "Kids 10–16" };
const T_MINI_GROUP = { ru: "Мини-группа · 3+", ro: "Mini-grup · 3+", en: "Mini group · 3+" };
const T_WOMEN_MINI = {
  ru: "Мини-группа для девушек",
  ro: "Mini-grup pentru femei",
  en: "Women's mini group",
};
const T_PERSONAL = { ru: "Персонально", ro: "Individual", en: "Personal training" };

const slot = (
  id: string,
  dayOfWeek: number,
  time: string,
  title: Record<string, string>,
  audience: ScheduleSlot["audience"],
  sortOrder: number,
  byArrangement = false,
): ScheduleSlot => ({
  id,
  dayOfWeek,
  time,
  byArrangement,
  title,
  coachId: null,
  coachName: null,
  level: null,
  audience,
  ageLabel: null,
  hall: null,
  note: null,
  active: true,
  sortOrder,
});

export const scheduleSlots: ScheduleSlot[] = [
  slot("mon-1", 0, "17:00", T_KIDS_59, "kids", 1),
  slot("mon-2", 0, "18:00", T_KIDS_1016, "kids", 2),
  slot("mon-3", 0, "19:00", T_GROUP, "all", 3),
  slot("tue-1", 1, "09:00 / 12:00", T_MINI_GROUP, "all", 1),
  slot("tue-2", 1, "19:00", T_WOMEN_MINI, "women", 2),
  slot("wed-1", 2, "17:00", T_KIDS_59, "kids", 1),
  slot("wed-2", 2, "18:00", T_KIDS_1016, "kids", 2),
  slot("wed-3", 2, "19:00", T_GROUP, "all", 3),
  slot("thu-1", 3, "09:00 / 12:00", T_MINI_GROUP, "all", 1),
  slot("thu-2", 3, "19:00", T_WOMEN_MINI, "women", 2),
  slot("fri-1", 4, "17:00", T_KIDS_59, "kids", 1),
  slot("fri-2", 4, "18:00", T_KIDS_1016, "kids", 2),
  slot("fri-3", 4, "19:00", T_GROUP, "all", 3),
  slot("sat-1", 5, "11:00", T_WOMEN_MINI, "women", 1),
  slot("sun-1", 6, "", T_PERSONAL, "all", 1, true),
];

export const galleryImages: GalleryImage[] = [
  {
    id: "g1",
    src: "/gallery/gallery-1.webp",
    alt: {
      ru: "Ринг и груши в зале Cangur Boxing Club с неоновой подсветкой",
      ro: "Ring și saci de box în sala Cangur Boxing Club, cu iluminare neon",
      en: "Ring and heavy bags at Cangur Boxing Club under neon lighting",
    },
    caption: null,
    active: true,
    sortOrder: 1,
  },
  {
    id: "g2",
    src: "/gallery/gallery-2.webp",
    alt: {
      ru: "Зона отдыха и витрина с экипировкой в Cangur Boxing Club",
      ro: "Zonă de relaxare și vitrină cu echipament la Cangur Boxing Club",
      en: "Lounge area and equipment display at Cangur Boxing Club",
    },
    caption: null,
    active: true,
    sortOrder: 2,
  },
  {
    id: "g3",
    src: "/gallery/gallery-3.webp",
    alt: {
      ru: "Боксёрский ринг с грушами под неоновой рамкой в клубе Cangur",
      ro: "Ring de box cu saci sub o ramă neon în clubul Cangur",
      en: "Boxing ring with bags under a neon frame at Cangur club",
    },
    caption: null,
    active: true,
    sortOrder: 3,
  },
  {
    id: "g4",
    src: "/gallery/gallery-4.webp",
    alt: {
      ru: "Силовая зона со штангой и гантелями рядом с рингом",
      ro: "Zonă de forță cu bară și gantere lângă ring",
      en: "Strength area with barbell and dumbbells next to the ring",
    },
    caption: null,
    active: true,
    sortOrder: 4,
  },
  {
    id: "g5",
    src: "/gallery/gallery-5.webp",
    alt: {
      ru: "Функциональная зона тренировок с кардиотренажёрами и инвентарём",
      ro: "Zonă de antrenament funcțional cu aparate cardio și inventar",
      en: "Functional training area with cardio machines and equipment",
    },
    caption: null,
    active: true,
    sortOrder: 5,
  },
  {
    id: "g6",
    src: "/gallery/gallery-6.webp",
    alt: {
      ru: "Угол ринга с канатами в зале Cangur Boxing Club",
      ro: "Colț de ring cu corzi în sala Cangur Boxing Club",
      en: "Ring corner with ropes at Cangur Boxing Club",
    },
    caption: null,
    active: true,
    sortOrder: 6,
  },
  {
    id: "g7",
    src: "/gallery/gallery-7.webp",
    alt: {
      ru: "Зеркальный зал с отражением ринга и тренажёров",
      ro: "Sală cu oglinzi în care se reflectă ringul și aparatele",
      en: "Mirrored hall reflecting the ring and machines",
    },
    caption: null,
    active: true,
    sortOrder: 7,
  },
];

export const products: Product[] = [
  {
    id: "glove-black",
    slug: "black",
    title: { ru: "12th Round Black", ro: "12th Round Black", en: "12th Round Black" },
    spec: { ru: "12 oz · Чёрные", ro: "12 oz · Negre", en: "12 oz · Black" },
    description: null,
    price: 1300,
    oldPrice: null,
    currency: "MDL",
    image: "/shop/glove-black.webp",
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 1,
  },
  {
    id: "glove-pink",
    slug: "pink",
    title: { ru: "12th Round Pink", ro: "12th Round Pink", en: "12th Round Pink" },
    spec: { ru: "12 oz · Розовые", ro: "12 oz · Roz", en: "12 oz · Pink" },
    description: null,
    price: 1300,
    oldPrice: null,
    currency: "MDL",
    image: "/shop/glove-pink.webp",
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 2,
  },
  {
    id: "glove-white",
    slug: "white",
    title: { ru: "12th Round White", ro: "12th Round White", en: "12th Round White" },
    spec: { ru: "12 oz · Белые", ro: "12 oz · Albe", en: "12 oz · White" },
    description: null,
    price: 1300,
    oldPrice: null,
    currency: "MDL",
    image: "/shop/glove-white.webp",
    ctaLabel: null,
    ctaUrl: null,
    active: true,
    sortOrder: 3,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "r1",
    text: {
      ru: "«Пришёл без опыта. Через несколько недель уже почувствовал технику и уверенность.»",
      ro: "«Am venit fără experiență. După câteva săptămâni am simțit deja progresul.»",
      en: "“I came with no experience. After a few weeks I already felt real progress.”",
    },
    author: "Alex",
    avatar: null,
    active: true,
    sortOrder: 1,
  },
  {
    id: "r2",
    text: {
      ru: "«Ребёнок ходит с удовольствием. Хорошая атмосфера и внимательный тренер.»",
      ro: "«Copilul vine cu plăcere. Atmosferă bună și antrenor atent.»",
      en: "“My child enjoys every session. Great atmosphere and an attentive coach.”",
    },
    author: "Maria",
    avatar: null,
    active: true,
    sortOrder: 2,
  },
  {
    id: "r3",
    text: {
      ru: "«Персональные тренировки дают очень быстрый прогресс.»",
      ro: "«Antrenamentele individuale oferă progres rapid.»",
      en: "“Personal training gives very fast progress.”",
    },
    author: "Victor",
    avatar: null,
    active: true,
    sortOrder: 3,
  },
];

export const coaches: Coach[] = [];
export const advertisements: Advertisement[] = [];
